name: flutter_widget_from_html
version: 0.8.5
description: Flutter package to render html as widgets that supports hyperlink, image, audio, video, iframe and many other tags.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.8.0"
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.8.5+3
  fwfh_cached_network_image:
    path: ../fwfh_cached_network_image
  fwfh_chewie:
    path: ../fwfh_chewie
  fwfh_just_audio:
    path: ../fwfh_just_audio
  fwfh_selectable_text:
    path: ../fwfh_selectable_text
  fwfh_svg:
    path: ../fwfh_svg
  fwfh_url_launcher:
    path: ../fwfh_url_launcher
  fwfh_webview:
    path: ../fwfh_webview
  html: ^0.15.0

dev_dependencies:
  file:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  lint: any
  mocktail: ^0.3.0

flutter:
  assets:
    - test/images/
